# Generated by Django 5.2.11 on 2026-03-03 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="exam",
            new_name="exams_exam_is_acti_924dcf_idx",
            old_name="exams_exam_is_acti_2efcf6_idx",
        ),
        migrations.RenameIndex(
            model_name="result",
            new_name="exams_resul_exam_id_3cc1cc_idx",
            old_name="exams_resul_exam_id_474359_idx",
        ),
        migrations.RenameIndex(
            model_name="result",
            new_name="exams_resul_student_40aedf_idx",
            old_name="exams_resul_student_801c6a_idx",
        ),
    ]
